version: 2.1
jobs:
  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:13-buster
    steps:
      - checkout
      - run: scp -o StrictHostKeyChecking=no deploy.sh ubuntu@3.125.21.233:~/deploy.sh
      - run: ssh -o StrictHostKeyChecking=no ubuntu@3.125.21.233 -f "chmod 777 ~/deploy.sh && nohup sudo ~/deploy.sh"


workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy