version: 2
jobs:
  build:

    working_directory: .
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: java-spring-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: java-spring-{{ checksum "pom.xml" }}

      - run: mvn package

workflows:
  version: 2
  build-deploy:
    jobs:
      - build