version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: java-spring-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: java-spring-{{ checksum "pom.xml" }}

      - run: mvn package

  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - run: ssh ubuntu@ec2-18-197-48-238.eu-central-1.compute.amazonaws.com 'bash -s' < aws.sh


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build