version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: java-spring-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: java-spring-{{ checksum "pom.xml" }}

      - run: mvn package

  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - run: scp aws.sh ubuntu@3.125.21.233:~/aws.sh
      - run: ssh -o StrictHostKeyChecking=no ubuntu@3.125.21.233
      - run: sudo ./aws.sh &


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build